server:
  servlet:
    context-path: /api
  port: 8087
app:
  host: http://app.zeeven.com
spring:
    application:
      name: ms-zeeven
    mail:
      activation-url: ${app.host}/activer-mon-compte?code=
      password-url: ${app.host}/activer-mon-compte?code=
      new-password-url: ${app.host}/activer-mon-compte?code=
      host: localhost
      port: 25
      properties:
        mail:
          smtp:
            port: 25
          transport:
            protocol: 'smtp'
            auth: true
            starttls:
              enable: true
              required: true

mongock:
  migration-scan-package:
    - com.cs.ge.configuration

jwt:
  header: "Authorization"
  secret: "AL_KEY"
  expiration: 3600 # (secondes) == 1 heure
  route:
    authentication:
      path: "/login"
      refresh: "/refresh"

