app:
  host: http://localhost:3000
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: zeeven

  mail:
      accountLink: ${app.host}/activer-mon-compte?code=








